spring:
  application:
    name: zxf-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengxf/zxf_cloud_config/      # 配置git仓库的地址
          search-paths: config-repo1                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码
        #native:    # 本地配置
        #  searchLocations: file:M:/project/zxf_super_demo/spring-demo/spring-cloud-demo/cloud-config-demo/config-repo
    bus:
      trace:
        enabled: true                        # 跟踪总线事件
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

# 关闭安全验证
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址

        
# content view => http://localhost:8001/neo-config-dev.properties
# api view => http://localhost:8001/neo-config/pro
# api view develop => http://localhost:8001/neo-config/dev/develop

# 跟踪总线事件 view => http://localhost:8001/trace

# 刷新 所有的 => curl -X POST http://127.0.0.1:8001/bus/refresh
# 刷新 特定的 => curl -X POST http://127.0.0.1:8001/bus/refresh?destination=zxf-cloud-config-client:**
# 刷新 单个的 => curl -X POST http://127.0.0.1:8001/bus/refresh?destination=zxf-cloud-config-client:default,c6:8006	# 需要根据 /trace 查找
