# 这个才是默认的
server:
  desc: test-aa
---
spring:
  profiles: default
  dubbo:
    application:
      name: demo-server
    protocol:
      name: dubbo
      serialization: fastjson
      host: 127.0.0.1
      port: 20886
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: cn.test.api
server:
  port: 8890
  desc: test-def
---
spring:
  profiles: test
  dubbo: # Dubbo
    application:
      name: demo-server-test
    protocol:
      name: dubbo
      serialization: fastjson
      host: 127.0.0.1
      port: 20887
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: cn.test.api
server:
  port: 8891
  desc: test-test
