server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# 测试
# http://localhost:8088/test/address?num=5
# http://localhost:8088/test/address?num=12
# http://localhost:8088/test/reload