spring:
  application:
    name: gateway-service-zuul
    
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      
zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.baidu.com/
    zxf-test:
      path: /test/**
      url: http://localhost:9000/
    zxf-test-api:
      path: /test-api/**
      serviceId: zxf-cloud-producer
      

# 访问 /it/** 直接重定向到http://www.baidu.com/**
# baidu view => http://127.0.0.1:8888/it/s?wd=test
# test view  => http://127.0.0.1:8888/test/hello?name=33
# test view  => http://127.0.0.1:8888/test-api/hello?name=7777
# test view  => http://127.0.0.1:8888/zxf-cloud-producer/hello?name=566666		# 默认是服务名