security:
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
      
  user:
    name: admin
    password: admin
      
      
server:
  port: 9999
  contextPath: /uaa