---
spring:
  application:
    name: zxf-cloud-eureka-012
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/
---
spring:
  application:
    name: zxf-cloud-eureka-012
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.1:8002/eureka/
---
spring:
  application:
    name: zxf-cloud-eureka-012
  profiles: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.1:8001/eureka/
