server:
  port: 9080
spring:
  messages:
    encoding: UTF-8
zxf:
  def: def-test
  custom: custom-def
  
---
# dev
spring:
  profiles: dev
zxf:
  custom: custom-dev
dubbo:
  name: dubbo-dev
  
---
# dubbo
spring:
  profiles: dubbo
dubbo:
  name: dubbo-dubbo

---
# dubbo-test
spring:
  profiles: dubbo-test
dubbo:
  name: dubbo-dubbo-test