server:
  port: 8001
  
spring:
  application:
    name: zxf-cloud-config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengxf/zxf_cloud_config/   # 配置git仓库的地址
          search-paths: config-repo1                                # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                                 # git仓库的账号
          password:                                                 # git仓库的密码
        #native:    # 本地配置
        #  searchLocations: file:M:/project/zxf_super_demo/spring-demo/spring-cloud-demo/cloud-config-demo/config-repo


#spring.profiles.active=native 直接是项目里的文件
        
# content view => http://localhost:8001/neo-config-dev.properties
# api view => http://localhost:8001/neo-config/pro
# api view develop => http://localhost:8001/neo-config/dev/develop