
---
spring:
  profiles: qing_long
app:
  id: 青龙
server:
  port: 9081
banner:
  location: classpath:banner-qing-long.txt
  
---
spring:
  profiles: bai_hu
app:
  id: 白虎
server:
  port: 9082
banner:
  location: classpath:banner-bai-hu.txt