spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO

---
spring:
  profiles: init
  datasource:
    data: sql/initialize-user.sql
    initialization-mode: always
    continue-on-error: false
