spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc
  jpa:
    show-sql: true
    hibernate:
      dialect:
        storage_engine: innodb
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true 

logging:
  level:
    root: INFO
