  
spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      
server:
  port: 8088
      
      
---

spring:
  profiles: unit
  data:
    mongodb:
      uri: mongodb://localhost:27017/test-unit
      
server:
  port: 8089
  