server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    database: 2

security:
  oauth2:
    resource:
      filter-order: 3
      
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
